language: python
python:
  - 3.7.7
services:
  - docker
install:
  - echo "No dependencies to be installed."
before_script:
  - echo "No tests to run"
script:
  - docker build -t meme-generator .
after_success:
  - docker tag meme-generator $DOCKER_USERNAME/meme-generator:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/meme-generator:latest
